version: "3.9"

services:
  backend:
    build:
      context: https://github.com/donaptello/de-tools-api.git
    container_name: de-tools-backend
    env_file:
      - ./.backend.env
    ports:
      - "8567:8567"
    expose:
      - "8567"
    volumes:
      - resources:/app/resources
    restart: unless-stopped

  frontend:
    build:
      context: .
      args:
        VITE_DE_TOOLS_API: http://localhost:8567
        VITE_SECRET_KEY: testing
        VITE_ALGORITM_KEY: HS256
    container_name: de-tools-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped